import { AlphabetLetter, SyllableWord, GameWord, SimpleSentence } from './types';

export const alphabetData: AlphabetLetter[] = [
  {
    char: 'A',
    wordExample: 'Apel',
    emoji: '🍎',
    category: 'vokal',
    color: 'bg-rose-100 hover:bg-rose-200',
    textColor: 'text-rose-600',
    borderColor: 'border-rose-300',
    accentColor: 'bg-rose-500',
  },
  {
    char: 'B',
    wordExample: 'Buku',
    emoji: '📘',
    category: 'konsonan',
    color: 'bg-sky-100 hover:bg-sky-200',
    textColor: 'text-sky-600',
    borderColor: 'border-sky-300',
    accentColor: 'bg-sky-500',
  },
  {
    char: 'C',
    wordExample: 'Ceri',
    emoji: '🍒',
    category: 'konsonan',
    color: 'bg-pink-100 hover:bg-pink-200',
    textColor: 'text-pink-600',
    borderColor: 'border-pink-300',
    accentColor: 'bg-pink-500',
  },
  {
    char: 'D',
    wordExample: 'Domba',
    emoji: '🐑',
    category: 'konsonan',
    color: 'bg-amber-100 hover:bg-amber-200',
    textColor: 'text-amber-600',
    borderColor: 'border-amber-300',
    accentColor: 'bg-amber-500',
  },
  {
    char: 'E',
    wordExample: 'Elang',
    emoji: '🦅',
    category: 'vokal',
    color: 'bg-indigo-100 hover:bg-indigo-200',
    textColor: 'text-indigo-600',
    borderColor: 'border-indigo-300',
    accentColor: 'bg-indigo-500',
  },
  {
    char: 'F',
    wordExample: 'Foto',
    emoji: '📸',
    category: 'konsonan',
    color: 'bg-purple-100 hover:bg-purple-200',
    textColor: 'text-purple-600',
    borderColor: 'border-purple-300',
    accentColor: 'bg-purple-500',
  },
  {
    char: 'G',
    wordExample: 'Gajah',
    emoji: '🐘',
    category: 'konsonan',
    color: 'bg-emerald-100 hover:bg-emerald-200',
    textColor: 'text-emerald-600',
    borderColor: 'border-emerald-300',
    accentColor: 'bg-emerald-500',
  },
  {
    char: 'H',
    wordExample: 'Harimau',
    emoji: '🐯',
    category: 'konsonan',
    color: 'bg-orange-100 hover:bg-orange-200',
    textColor: 'text-orange-600',
    borderColor: 'border-orange-300',
    accentColor: 'bg-orange-500',
  },
  {
    char: 'I',
    wordExample: 'Ikan',
    emoji: '🐟',
    category: 'vokal',
    color: 'bg-blue-100 hover:bg-blue-200',
    textColor: 'text-blue-600',
    borderColor: 'border-blue-300',
    accentColor: 'bg-blue-500',
  },
  {
    char: 'J',
    wordExample: 'Jeruk',
    emoji: '🍊',
    category: 'konsonan',
    color: 'bg-amber-100 hover:bg-amber-200',
    textColor: 'text-amber-600',
    borderColor: 'border-amber-300',
    accentColor: 'bg-amber-500',
  },
  {
    char: 'K',
    wordExample: 'Kucing',
    emoji: '🐱',
    category: 'konsonan',
    color: 'bg-yellow-100 hover:bg-yellow-200',
    textColor: 'text-yellow-600',
    borderColor: 'border-yellow-300',
    accentColor: 'bg-yellow-500',
  },
  {
    char: 'L',
    wordExample: 'Lebah',
    emoji: '🐝',
    category: 'konsonan',
    color: 'bg-lime-100 hover:bg-lime-200',
    textColor: 'text-lime-600',
    borderColor: 'border-lime-300',
    accentColor: 'bg-lime-500',
  },
  {
    char: 'M',
    wordExample: 'Mangga',
    emoji: '🥭',
    category: 'konsonan',
    color: 'bg-orange-500/10 hover:bg-orange-500/20',
    textColor: 'text-orange-700',
    borderColor: 'border-orange-300',
    accentColor: 'bg-orange-600',
  },
  {
    char: 'N',
    wordExample: 'Nanas',
    emoji: '🍍',
    category: 'konsonan',
    color: 'bg-yellow-100 hover:bg-yellow-200',
    textColor: 'text-yellow-700',
    borderColor: 'border-yellow-400',
    accentColor: 'bg-yellow-600',
  },
  {
    char: 'O',
    wordExample: 'Obor',
    emoji: '🔥',
    category: 'vokal',
    color: 'bg-red-100 hover:bg-red-200',
    textColor: 'text-red-600',
    borderColor: 'border-red-300',
    accentColor: 'bg-red-500',
  },
  {
    char: 'P',
    wordExample: 'Pisang',
    emoji: '🍌',
    category: 'konsonan',
    color: 'bg-yellow-500/10 hover:bg-yellow-500/20',
    textColor: 'text-yellow-600',
    borderColor: 'border-yellow-300',
    accentColor: 'bg-yellow-500',
  },
  {
    char: 'Q',
    wordExample: 'Quran',
    emoji: '📖',
    category: 'konsonan',
    color: 'bg-teal-100 hover:bg-teal-200',
    textColor: 'text-teal-600',
    borderColor: 'border-teal-300',
    accentColor: 'bg-teal-500',
  },
  {
    char: 'R',
    wordExample: 'Rusa',
    emoji: '🦌',
    category: 'konsonan',
    color: 'bg-stone-100 hover:bg-stone-200',
    textColor: 'text-stone-600',
    borderColor: 'border-stone-300',
    accentColor: 'bg-stone-500',
  },
  {
    char: 'S',
    wordExample: 'Sapi',
    emoji: '🐄',
    category: 'konsonan',
    color: 'bg-neutral-100 hover:bg-neutral-200',
    textColor: 'text-neutral-600',
    borderColor: 'border-neutral-300',
    accentColor: 'bg-neutral-500',
  },
  {
    char: 'T',
    wordExample: 'Topi',
    emoji: '🧢',
    category: 'konsonan',
    color: 'bg-violet-100 hover:bg-violet-200',
    textColor: 'text-violet-600',
    borderColor: 'border-violet-300',
    accentColor: 'bg-violet-500',
  },
  {
    char: 'U',
    wordExample: 'Unta',
    emoji: '🐪',
    category: 'vokal',
    color: 'bg-orange-50 hover:bg-orange-100',
    textColor: 'text-orange-600',
    borderColor: 'border-orange-200',
    accentColor: 'bg-orange-500',
  },
  {
    char: 'V',
    wordExample: 'Vespa',
    emoji: '🛵',
    category: 'konsonan',
    color: 'bg-teal-50 hover:bg-teal-100',
    textColor: 'text-teal-600',
    borderColor: 'border-teal-200',
    accentColor: 'bg-teal-500',
  },
  {
    char: 'W',
    wordExample: 'Wortel',
    emoji: '🥕',
    category: 'konsonan',
    color: 'bg-orange-100 hover:bg-orange-200',
    textColor: 'text-orange-600',
    borderColor: 'border-orange-300',
    accentColor: 'bg-orange-500',
  },
  {
    char: 'X',
    wordExample: 'Xilofon',
    emoji: '🎶',
    category: 'konsonan',
    color: 'bg-indigo-50 hover:bg-indigo-100',
    textColor: 'text-indigo-600',
    borderColor: 'border-indigo-200',
    accentColor: 'bg-indigo-500',
  },
  {
    char: 'Y',
    wordExample: 'Yoyo',
    emoji: '🪀',
    category: 'konsonan',
    color: 'bg-fuchsia-100 hover:bg-fuchsia-200',
    textColor: 'text-fuchsia-600',
    borderColor: 'border-fuchsia-300',
    accentColor: 'bg-fuchsia-500',
  },
  {
    char: 'Z',
    wordExample: 'Zebra',
    emoji: '🦓',
    category: 'konsonan',
    color: 'bg-neutral-200 hover:bg-neutral-300',
    textColor: 'text-neutral-800',
    borderColor: 'border-neutral-400',
    accentColor: 'bg-neutral-700',
  },
];

export const syllableWordsData: SyllableWord[] = [
  {
    word: 'Ayah',
    syllables: ['A', 'yah'],
    emoji: '👨',
    category: 'Keluarga',
    color: 'from-orange-400 to-amber-500',
  },
  {
    word: 'Ibu',
    syllables: ['I', 'bu'],
    emoji: '👩',
    category: 'Keluarga',
    color: 'from-pink-400 to-rose-500',
  },
  {
    word: 'Bola',
    syllables: ['Bo', 'la'],
    emoji: '⚽',
    category: 'Mainan',
    color: 'from-sky-400 to-blue-500',
  },
  {
    word: 'Buku',
    syllables: ['Bu', 'ku'],
    emoji: '📖',
    category: 'Sekolah',
    color: 'from-emerald-400 to-teal-500',
  },
  {
    word: 'Sapi',
    syllables: ['Sa', 'pi'],
    emoji: '🐄',
    category: 'Hewan',
    color: 'from-violet-400 to-purple-500',
  },
  {
    word: 'Topi',
    syllables: ['To', 'pi'],
    emoji: '🧢',
    category: 'Pakaian',
    color: 'from-fuchsia-400 to-pink-500',
  },
  {
    word: 'Madu',
    syllables: ['Ma', 'du'],
    emoji: '🍯',
    category: 'Makanan',
    color: 'from-yellow-400 to-amber-500',
  },
  {
    word: 'Roti',
    syllables: ['Ro', 'ti'],
    emoji: '🍞',
    category: 'Makanan',
    color: 'from-orange-300 to-amber-600',
  },
  {
    word: 'Kucing',
    syllables: ['Ku', 'cing'],
    emoji: '🐱',
    category: 'Hewan',
    color: 'from-yellow-400 to-orange-500',
  },
  {
    word: 'Gajah',
    syllables: ['Ga', 'jah'],
    emoji: '🐘',
    category: 'Hewan',
    color: 'from-slate-400 to-stone-500',
  },
  {
    word: 'Meja',
    syllables: ['Me', 'ja'],
    emoji: '🪑',
    category: 'Sekolah',
    color: 'from-amber-500 to-amber-700',
  },
  {
    word: 'Sepeda',
    syllables: ['Se', 'pe', 'da'],
    emoji: '🚲',
    category: 'Lainnya',
    color: 'from-indigo-400 to-blue-500',
  },
  {
    word: 'Boneka',
    syllables: ['Bo', 'ne', 'ka'],
    emoji: '🧸',
    category: 'Mainan',
    color: 'from-rose-400 to-pink-500',
  },
  {
    word: 'Palu',
    syllables: ['Pa', 'lu'],
    emoji: '🔨',
    category: 'Benda',
    color: 'from-stone-400 to-stone-600',
  },
  {
    word: 'Lampu',
    syllables: ['Lam', 'pu'],
    emoji: '💡',
    category: 'Rumah',
    color: 'from-yellow-300 to-yellow-500',
  },
  {
    word: 'Batu',
    syllables: ['Ba', 'tu'],
    emoji: '🪨',
    category: 'Alam',
    color: 'from-zinc-400 to-zinc-600',
  },
  {
    word: 'Susu',
    syllables: ['Su', 'su'],
    emoji: '🥛',
    category: 'Makanan',
    color: 'from-sky-300 to-indigo-400',
  },
  {
    word: 'Nasi',
    syllables: ['Na', 'si'],
    emoji: '🍚',
    category: 'Makanan',
    color: 'from-slate-200 to-slate-400',
  },
  {
    word: 'Keju',
    syllables: ['Ke', 'ju'],
    emoji: '🧀',
    category: 'Makanan',
    color: 'from-amber-400 to-yellow-500',
  },
  {
    word: 'Mata',
    syllables: ['Ma', 'ta'],
    emoji: '👁️',
    category: 'Tubuh',
    color: 'from-pink-300 to-rose-400',
  },
  {
    word: 'Kaki',
    syllables: ['Ka', 'ki'],
    emoji: '👣',
    category: 'Tubuh',
    color: 'from-teal-300 to-teal-500',
  },
  {
    word: 'Gigi',
    syllables: ['Gi', 'gi'],
    emoji: '🦷',
    category: 'Tubuh',
    color: 'from-blue-200 to-blue-400',
  },
  {
    word: 'Pipi',
    syllables: ['Pi', 'pi'],
    emoji: '😊',
    category: 'Tubuh',
    color: 'from-rose-300 to-pink-400',
  },
  {
    word: 'Dasi',
    syllables: ['Da', 'si'],
    emoji: '👔',
    category: 'Pakaian',
    color: 'from-blue-400 to-indigo-500',
  },
  {
    word: 'Baju',
    syllables: ['Ba', 'ju'],
    emoji: '👕',
    category: 'Pakaian',
    color: 'from-emerald-400 to-cyan-500',
  },
  {
    word: 'Pena',
    syllables: ['Pe', 'na'],
    emoji: '🖊️',
    category: 'Sekolah',
    color: 'from-gray-400 to-gray-600',
  },
  {
    word: 'Peta',
    syllables: ['Pe', 'ta'],
    emoji: '🗺️',
    category: 'Sekolah',
    color: 'from-orange-400 to-amber-500',
  },
  {
    word: 'Tisu',
    syllables: ['Ti', 'su'],
    emoji: '🧻',
    category: 'Rumah',
    color: 'from-slate-100 to-slate-350',
  },
  {
    word: 'Adik',
    syllables: ['A', 'dik'],
    emoji: '👶',
    category: 'Keluarga',
    color: 'from-teal-400 to-green-500',
  },
  {
    word: 'Kakak',
    syllables: ['Ka', 'kak'],
    emoji: '🧑',
    category: 'Keluarga',
    color: 'from-purple-400 to-blue-500',
  },
  {
    word: 'Pita',
    syllables: ['Pi', 'ta'],
    emoji: '🎀',
    category: 'Mainan',
    color: 'from-rose-400 to-pink-500',
  },
  {
    word: 'Bata',
    syllables: ['Ba', 'ta'],
    emoji: '🧱',
    category: 'Benda',
    color: 'from-red-400 to-orange-500',
  },
  {
    word: 'Dadu',
    syllables: ['Da', 'du'],
    emoji: '🎲',
    category: 'Mainan',
    color: 'from-violet-400 to-indigo-500',
  },
  {
    word: 'Kopi',
    syllables: ['Ko', 'pi'],
    emoji: '☕',
    category: 'Makanan',
    color: 'from-amber-700 to-yellow-800',
  },
  {
    word: 'Jeli',
    syllables: ['Je', 'li'],
    emoji: '🍮',
    category: 'Makanan',
    color: 'from-fuchsia-400 to-rose-450',
  },
  {
    word: 'Paku',
    syllables: ['Pa', 'ku'],
    emoji: '📍',
    category: 'Benda',
    color: 'from-zinc-400 to-slate-500',
  },
  {
    word: 'Saku',
    syllables: ['Sa', 'ku'],
    emoji: '👛',
    category: 'Pakaian',
    color: 'from-pink-300 to-rose-450',
  },
  {
    word: 'Tali',
    syllables: ['Ta', 'li'],
    emoji: '🪢',
    category: 'Benda',
    color: 'from-orange-400 to-yellow-500',
  },
  {
    word: 'Raja',
    syllables: ['Ra', 'ja'],
    emoji: '👑',
    category: 'Keluarga',
    color: 'from-amber-400 to-yellow-500',
  },
  {
    word: 'Ratu',
    syllables: ['Ra', 'tu'],
    emoji: '👸',
    category: 'Keluarga',
    color: 'from-pink-400 to-purple-500',
  },
  {
    word: 'Feri',
    syllables: ['Fe', 'ri'],
    emoji: '🚢',
    category: 'Lainnya',
    color: 'from-cyan-400 to-blue-500',
  },
  {
    word: 'Taksi',
    syllables: ['Tak', 'si'],
    emoji: '🚖',
    category: 'Lainnya',
    color: 'from-yellow-400 to-amber-500',
  },
  {
    word: 'Kuda',
    syllables: ['Ku', 'da'],
    emoji: '🐎',
    category: 'Hewan',
    color: 'from-amber-600 to-orange-700',
  },
  {
    word: 'Singa',
    syllables: ['Si', 'nga'],
    emoji: '🦁',
    category: 'Hewan',
    color: 'from-yellow-500 to-amber-600',
  },
  {
    word: 'Rusa',
    syllables: ['Ru', 'sa'],
    emoji: '🦌',
    category: 'Hewan',
    color: 'from-emerald-450 to-amber-600',
  },
  {
    word: 'Panda',
    syllables: ['Pan', 'da'],
    emoji: '🐼',
    category: 'Hewan',
    color: 'from-neutral-400 to-neutral-600',
  },
  {
    word: 'Padi',
    syllables: ['Pa', 'di'],
    emoji: '🌾',
    category: 'Alam',
    color: 'from-lime-400 to-yellow-500',
  },
  {
    word: 'Bunga',
    syllables: ['Bu', 'nga'],
    emoji: '🌸',
    category: 'Alam',
    color: 'from-rose-400 to-pink-500',
  },
  {
    word: 'Ceri',
    syllables: ['Ce', 'ri'],
    emoji: '🍒',
    category: 'Buah',
    color: 'from-red-500 to-rose-600',
  },
  {
    word: 'Apel',
    syllables: ['A', 'pel'],
    emoji: '🍎',
    category: 'Buah',
    color: 'from-rose-500 to-red-650',
  },
  {
    word: 'Nanas',
    syllables: ['Na', 'nas'],
    emoji: '🍍',
    category: 'Buah',
    color: 'from-yellow-400 to-lime-500',
  },
  {
    word: 'Melon',
    syllables: ['Me', 'lon'],
    emoji: '🍈',
    category: 'Buah',
    color: 'from-green-405 to-lime-400',
  },
  {
    word: 'Leci',
    syllables: ['Le', 'ci'],
    emoji: '🍒',
    category: 'Buah',
    color: 'from-rose-400 to-red-500',
  },
  {
    word: 'Labu',
    syllables: ['La', 'bu'],
    emoji: '🎃',
    category: 'Sayuran',
    color: 'from-orange-400 to-amber-500',
  },
  {
    word: 'Sawi',
    syllables: ['Sa', 'wi'],
    emoji: '🥬',
    category: 'Sayuran',
    color: 'from-green-400 to-emerald-500',
  },
  {
    word: 'Bayam',
    syllables: ['Ba', 'yam'],
    emoji: '🌿',
    category: 'Sayuran',
    color: 'from-emerald-400 to-teal-500',
  },
  {
    word: 'Cabe',
    syllables: ['Ca', 'be'],
    emoji: '🌶️',
    category: 'Sayuran',
    color: 'from-red-500 to-rose-600',
  },
  {
    word: 'Tahu',
    syllables: ['Ta', 'hu'],
    emoji: '⬜',
    category: 'Makanan',
    color: 'from-slate-100 to-gray-200',
  },
  {
    word: 'Tempe',
    syllables: ['Tem', 'pe'],
    emoji: '🪵',
    category: 'Makanan',
    color: 'from-amber-600 to-amber-800',
  },
  {
    word: 'Bolu',
    syllables: ['Bo', 'lu'],
    emoji: '🍰',
    category: 'Makanan',
    color: 'from-pink-400 to-rose-500',
  },
  {
    word: 'Soto',
    syllables: ['So', 'to'],
    emoji: '🍲',
    category: 'Makanan',
    color: 'from-yellow-450 to-amber-650',
  },
  {
    word: 'Sate',
    syllables: ['Sa', 'te'],
    emoji: '🍢',
    category: 'Makanan',
    color: 'from-orange-400 to-amber-600',
  },
  {
    word: 'Bakso',
    syllables: ['Bak', 'so'],
    emoji: '🍲',
    category: 'Makanan',
    color: 'from-stone-400 to-amber-750',
  },
  {
    word: 'Boba',
    syllables: ['Bo', 'ba'],
    emoji: '🧋',
    category: 'Makanan',
    color: 'from-rose-300 to-amber-400',
  },
  {
    word: 'Sirup',
    syllables: ['Si', 'rup'],
    emoji: '🥤',
    category: 'Makanan',
    color: 'from-red-400 to-rose-500',
  },
  {
    word: 'Sofa',
    syllables: ['So', 'fa'],
    emoji: '🛋️',
    category: 'Rumah',
    color: 'from-blue-400 to-indigo-500',
  },
  {
    word: 'Sapu',
    syllables: ['Sa', 'pu'],
    emoji: '🧹',
    category: 'Rumah',
    color: 'from-amber-400 to-yellow-600',
  },
  {
    word: 'Pintu',
    syllables: ['Pin', 'tu'],
    emoji: '🚪',
    category: 'Rumah',
    color: 'from-amber-750 to-orange-700',
  },
  {
    word: 'Bumi',
    syllables: ['Bu', 'mi'],
    emoji: '🌍',
    category: 'Alam',
    color: 'from-blue-450 to-green-500',
  },
  {
    word: 'Bulan',
    syllables: ['Bu', 'lan'],
    emoji: '🌙',
    category: 'Alam',
    color: 'from-indigo-400 to-violet-500',
  },
  {
    word: 'Sinar',
    syllables: ['Si', 'nar'],
    emoji: '☀️',
    category: 'Alam',
    color: 'from-yellow-400 to-amber-500',
  },
  {
    word: 'Awan',
    syllables: ['A', 'wan'],
    emoji: '☁️',
    category: 'Alam',
    color: 'from-sky-300 to-blue-400',
  },
  {
    word: 'Hujan',
    syllables: ['Hu', 'jan'],
    emoji: '🌧️',
    category: 'Alam',
    color: 'from-cyan-400 to-sky-500',
  },
  {
    word: 'Pohon',
    syllables: ['Po', 'hon'],
    emoji: '🌳',
    category: 'Alam',
    color: 'from-green-500 to-emerald-600',
  },
];

export const gameWordsData: GameWord[] = [
  {
    word: 'ayah',
    hint: 'Laki-laki pahlawan hebat di rumah kita',
    emoji: '👨',
    category: 'Keluarga',
    difficulty: 'mudah',
  },
  {
    word: 'ibu',
    hint: 'Perempuan penyayang yang melahirkan kita',
    emoji: '👩',
    category: 'Keluarga',
    difficulty: 'mudah',
  },
  {
    word: 'bola',
    hint: 'Benda bulat yang asik ditendang dan dimainkan',
    emoji: '⚽',
    category: 'Mainan',
    difficulty: 'mudah',
  },
  {
    word: 'buku',
    hint: 'Lembaran kertas penuh cerita gambarnya banyak',
    emoji: '📘',
    category: 'Sekolah',
    difficulty: 'mudah',
  },
  {
    word: 'sapi',
    hint: 'Hewan berkaki empat yang menghasilkan susu segar',
    emoji: '🐄',
    category: 'Hewan',
    difficulty: 'mudah',
  },
  {
    word: 'topi',
    hint: 'Dipakai di kepala agar tidak kepanasan matahari',
    emoji: '🧢',
    category: 'Pakaian',
    difficulty: 'mudah',
  },
  {
    word: 'kucing',
    hint: 'Hewan berbulu yang suaranya "meong.. meong..."',
    emoji: '🐱',
    category: 'Hewan',
    difficulty: 'sedang',
  },
  {
    word: 'gajah',
    hint: 'Hewan berbadan besar sekali dengan belalai panjang',
    emoji: '🐘',
    category: 'Hewan',
    difficulty: 'sedang',
  },
  {
    word: 'roti',
    hint: 'Makanan lezat bermacam selai untuk sarapan pagi',
    emoji: '🍞',
    category: 'Makanan',
    difficulty: 'mudah',
  },
  {
    word: 'madu',
    hint: 'Cairan manis lengket menyehatkan buatan lebah',
    emoji: '🍯',
    category: 'Makanan',
    difficulty: 'sedang',
  },
  {
    word: 'sepeda',
    hint: 'Kendaraan beroda dua yang jalannya dengan dikayuh',
    emoji: '🚲',
    category: 'Lainnya',
    difficulty: 'menantang',
  },
  {
    word: 'boneka',
    hint: 'Mainan berbentuk lucu, biasanya sangat empuk dipeluk',
    emoji: '🧸',
    category: 'Mainan',
    difficulty: 'menantang',
  },
  {
    word: 'pisang',
    hint: 'Buah berwarna kuning bergizi tinggi, kesukaan monyet',
    emoji: '🍌',
    category: 'Buah',
    difficulty: 'sedang',
  },
  {
    word: 'wortel',
    hint: 'Sayuran berwarna oranye menyehatkan mata kelinci',
    emoji: '🥕',
    category: 'Sayuran',
    difficulty: 'sedang',
  },
];

export const sentencesData: SimpleSentence[] = [
  {
    id: 's1',
    text: 'Ini ibu Budi',
    words: ['Ini', 'ibu', 'Budi'],
    emoji: '👩‍🏫',
    color: 'bg-rose-50 hover:bg-rose-100',
    textColor: 'text-rose-700',
    borderColor: 'border-rose-200',
    bgGradient: 'from-rose-400 to-pink-500',
  },
  {
    id: 's2',
    text: 'Budi main bola',
    words: ['Budi', 'main', 'bola'],
    emoji: '⚽🏃',
    color: 'bg-sky-50 hover:bg-sky-100',
    textColor: 'text-sky-700',
    borderColor: 'border-sky-200',
    bgGradient: 'from-sky-400 to-blue-500',
  },
  {
    id: 's3',
    text: 'Kucing makan ikan',
    words: ['Kucing', 'makan', 'ikan'],
    emoji: '🐱🐟',
    color: 'bg-amber-50 hover:bg-amber-100',
    textColor: 'text-amber-800',
    borderColor: 'border-amber-200',
    bgGradient: 'from-amber-400 to-orange-500',
  },
  {
    id: 's4',
    text: 'Adik minum susu',
    words: ['Adik', 'minum', 'susu'],
    emoji: '🍼👶',
    color: 'bg-teal-50 hover:bg-teal-100',
    textColor: 'text-teal-700',
    borderColor: 'border-teal-200',
    bgGradient: 'from-teal-400 to-emerald-500',
  },
  {
    id: 's5',
    text: 'Kakak menyanyi lagu',
    words: ['Kakak', 'menyanyi', 'lagu'],
    emoji: '🎤🎶',
    color: 'bg-fuchsia-50 hover:bg-fuchsia-100',
    textColor: 'text-fuchsia-700',
    borderColor: 'border-fuchsia-200',
    bgGradient: 'from-fuchsia-400 to-purple-500',
  },
  {
    id: 's6',
    text: 'Ayah naik sepeda',
    words: ['Ayah', 'naik', 'sepeda'],
    emoji: '🚲👨',
    color: 'bg-lime-50 hover:bg-lime-100',
    textColor: 'text-lime-700',
    borderColor: 'border-lime-200',
    bgGradient: 'from-lime-400 to-emerald-500',
  },
  {
    id: 's7',
    text: 'Bunga mawar merah',
    words: ['Bunga', 'mawar', 'merah'],
    emoji: '🌹❤️',
    color: 'bg-red-50 hover:bg-red-100',
    textColor: 'text-red-700',
    borderColor: 'border-red-200',
    bgGradient: 'from-red-400 to-rose-600',
  },
  {
    id: 's8',
    text: 'Burung terbang tinggi',
    words: ['Burung', 'terbang', 'tinggi'],
    emoji: '🐦☁️',
    color: 'bg-indigo-50 hover:bg-indigo-100',
    textColor: 'text-indigo-700',
    borderColor: 'border-indigo-200',
    bgGradient: 'from-indigo-400 to-violet-500',
  },
  {
    id: 's9',
    text: 'Zidan suka susu',
    words: ['Zidan', 'suka', 'susu'],
    emoji: '🍼🥛',
    color: 'bg-sky-50 hover:bg-sky-100',
    textColor: 'text-sky-700',
    borderColor: 'border-sky-200',
    bgGradient: 'from-sky-400 to-blue-500',
  },
  {
    id: 's10',
    text: 'Saya baca buku',
    words: ['Saya', 'baca', 'buku'],
    emoji: '📖✨',
    color: 'bg-emerald-50 hover:bg-emerald-100',
    textColor: 'text-emerald-700',
    borderColor: 'border-emerald-200',
    bgGradient: 'from-emerald-400 to-teal-500',
  },
  {
    id: 's11',
    text: 'Ibu masak nasi',
    words: ['Ibu', 'masak', 'nasi'],
    emoji: '🍚🍳',
    color: 'bg-rose-50 hover:bg-rose-100',
    textColor: 'text-rose-700',
    borderColor: 'border-rose-200',
    bgGradient: 'from-rose-400 to-red-500',
  },
  {
    id: 's12',
    text: 'Ayah beli madu',
    words: ['Ayah', 'beli', 'madu'],
    emoji: '🍯🐝',
    color: 'bg-amber-50 hover:bg-amber-100',
    textColor: 'text-amber-700',
    borderColor: 'border-amber-200',
    bgGradient: 'from-yellow-400 to-amber-500',
  },
  {
    id: 's13',
    text: 'Bola itu baru',
    words: ['Bola', 'itu', 'baru'],
    emoji: '⚽🆕',
    color: 'bg-teal-50 hover:bg-teal-100',
    textColor: 'text-teal-700',
    borderColor: 'border-teal-200',
    bgGradient: 'from-teal-400 to-cyan-500',
  },
  {
    id: 's14',
    text: 'Kucing tidur manis',
    words: ['Kucing', 'tidur', 'manis'],
    emoji: '🐱💤',
    color: 'bg-violet-50 hover:bg-violet-100',
    textColor: 'text-violet-750',
    borderColor: 'border-violet-200',
    bgGradient: 'from-violet-400 to-purple-500',
  },
  {
    id: 's15',
    text: 'Adik suka jeli',
    words: ['Adik', 'suka', 'jeli'],
    emoji: '🍮👶',
    color: 'bg-pink-50 hover:bg-pink-100',
    textColor: 'text-pink-700',
    borderColor: 'border-pink-200',
    bgGradient: 'from-pink-400 to-rose-550',
  },
  {
    id: 's16',
    text: 'Roti rasa keju',
    words: ['Roti', 'rasa', 'keju'],
    emoji: '🍞🧀',
    color: 'bg-yellow-50 hover:bg-yellow-100',
    textColor: 'text-yellow-700',
    borderColor: 'border-yellow-200',
    bgGradient: 'from-yellow-400 to-amber-500',
  },
  {
    id: 's17',
    text: 'Bunga mekar pagi',
    words: ['Bunga', 'mekar', 'pagi'],
    emoji: '🌸☀️',
    color: 'bg-rose-50 hover:bg-rose-100',
    textColor: 'text-rose-700',
    borderColor: 'border-rose-200',
    bgGradient: 'from-rose-400 to-pink-500',
  },
  {
    id: 's18',
    text: 'Sapi makan rumput',
    words: ['Sapi', 'makan', 'rumput'],
    emoji: '🐄🌾',
    color: 'bg-lime-50 hover:bg-lime-100',
    textColor: 'text-lime-800',
    borderColor: 'border-lime-200',
    bgGradient: 'from-lime-400 to-emerald-500',
  },
  {
    id: 's19',
    text: 'Mata saya dua',
    words: ['Mata', 'saya', 'dua'],
    emoji: '👁️✌️',
    color: 'bg-cyan-50 hover:bg-cyan-100',
    textColor: 'text-cyan-750',
    borderColor: 'border-cyan-200',
    bgGradient: 'from-cyan-400 to-blue-500',
  },
  {
    id: 's20',
    text: 'Kakak pakai dasi',
    words: ['Kakak', 'pakai', 'dasi'],
    emoji: '👔🧑',
    color: 'bg-indigo-50 hover:bg-indigo-100',
    textColor: 'text-indigo-700',
    borderColor: 'border-indigo-200',
    bgGradient: 'from-indigo-400 to-violet-500',
  },
  {
    id: 's21',
    text: 'Kuda lari cepat',
    words: ['Kuda', 'lari', 'cepat'],
    emoji: '🐎⚡',
    color: 'bg-amber-50 hover:bg-amber-100',
    textColor: 'text-amber-800',
    borderColor: 'border-amber-200',
    bgGradient: 'from-amber-500 to-orange-600',
  },
  {
    id: 's22',
    text: 'Gigi saya putih',
    words: ['Gigi', 'saya', 'putih'],
    emoji: '🦷✨',
    color: 'bg-slate-50 hover:bg-slate-100',
    textColor: 'text-slate-700',
    borderColor: 'border-slate-200',
    bgGradient: 'from-slate-400 to-gray-500',
  },
  {
    id: 's23',
    text: 'Kue bolu manis',
    words: ['Kue', 'bolu', 'manis'],
    emoji: '🍰🧁',
    color: 'bg-fuchsia-50 hover:bg-fuchsia-100',
    textColor: 'text-fuchsia-700',
    borderColor: 'border-fuchsia-200',
    bgGradient: 'from-fuchsia-400 to-pink-500',
  },
  {
    id: 's24',
    text: 'Pena merah baru',
    words: ['Pena', 'merah', 'baru'],
    emoji: '🖊️🔴',
    color: 'bg-red-50 hover:bg-red-100',
    textColor: 'text-red-700',
    borderColor: 'border-red-200',
    bgGradient: 'from-red-400 to-rose-600',
  },
  {
    id: 's25',
    text: 'Sapu di sudut',
    words: ['Sapu', 'di', 'sudut'],
    emoji: '🧹🚪',
    color: 'bg-emerald-50 hover:bg-emerald-100',
    textColor: 'text-emerald-700',
    borderColor: 'border-emerald-200',
    bgGradient: 'from-emerald-400 to-teal-500',
  },
  {
    id: 's26',
    text: 'Bumi itu bulat',
    words: ['Bumi', 'itu', 'bulat'],
    emoji: '🌍🔵',
    color: 'bg-blue-50 hover:bg-blue-100',
    textColor: 'text-blue-700',
    borderColor: 'border-blue-200',
    bgGradient: 'from-blue-400 to-indigo-500',
  },
  {
    id: 's27',
    text: 'Bulan bersinar terang',
    words: ['Bulan', 'bersinar', 'terang'],
    emoji: '🌙🌟',
    color: 'bg-violet-50 hover:bg-violet-100',
    textColor: 'text-violet-750',
    borderColor: 'border-violet-200',
    bgGradient: 'from-violet-400 to-purple-500',
  },
  {
    id: 's28',
    text: 'Awan putih lembut',
    words: ['Awan', 'putih', 'lembut'],
    emoji: '☁️☁️',
    color: 'bg-sky-50 hover:bg-sky-100',
    textColor: 'text-sky-700',
    borderColor: 'border-sky-200',
    bgGradient: 'from-sky-300 to-blue-400',
  },
  {
    id: 's29',
    text: 'Hujan turun deras',
    words: ['Hujan', 'turun', 'deras'],
    emoji: '🌧️💧',
    color: 'bg-cyan-50 hover:bg-cyan-100',
    textColor: 'text-cyan-700',
    borderColor: 'border-cyan-200',
    bgGradient: 'from-cyan-400 to-sky-500',
  },
  {
    id: 's30',
    text: 'Pohon tumbuh tinggi',
    words: ['Pohon', 'tumbuh', 'tinggi'],
    emoji: '🌳🌿',
    color: 'bg-green-50 hover:bg-green-100',
    textColor: 'text-green-700',
    borderColor: 'border-green-200',
    bgGradient: 'from-green-400 to-emerald-600',
  },
  {
    id: 's31',
    text: 'Lampu menyala terang',
    words: ['Lampu', 'menyala', 'terang'],
    emoji: '💡💡',
    color: 'bg-yellow-50 hover:bg-yellow-100',
    textColor: 'text-yellow-700',
    borderColor: 'border-yellow-200',
    bgGradient: 'from-yellow-300 to-amber-500',
  },
  {
    id: 's32',
    text: 'Batu kali hitam',
    words: ['Batu', 'kali', 'hitam'],
    emoji: '🪨◼️',
    color: 'bg-stone-50 hover:bg-stone-100',
    textColor: 'text-stone-700',
    borderColor: 'border-stone-200',
    bgGradient: 'from-stone-400 to-zinc-650',
  },
  {
    id: 's33',
    text: 'Topi saya biru',
    words: ['Topi', 'saya', 'biru'],
    emoji: '🧢🔵',
    color: 'bg-sky-50 hover:bg-sky-100',
    textColor: 'text-sky-700',
    borderColor: 'border-sky-200',
    bgGradient: 'from-sky-400 to-indigo-500',
  },
  {
    id: 's34',
    text: 'Sate rasa lezat',
    words: ['Sate', 'rasa', 'lezat'],
    emoji: '🍢😋',
    color: 'bg-orange-50 hover:bg-orange-100',
    textColor: 'text-orange-700',
    borderColor: 'border-orange-200',
    bgGradient: 'from-orange-400 to-red-500',
  },
  {
    id: 's35',
    text: 'Soto panas segar',
    words: ['Soto', 'panas', 'segar'],
    emoji: '🍲🔥',
    color: 'bg-amber-50 hover:bg-amber-100',
    textColor: 'text-amber-800',
    borderColor: 'border-amber-200',
    bgGradient: 'from-yellow-450 to-amber-600',
  },
  {
    id: 's36',
    text: 'Nanas kulit duri',
    words: ['Nanas', 'kulit', 'duri'],
    emoji: '🍍🛡️',
    color: 'bg-yellow-50 hover:bg-yellow-100',
    textColor: 'text-yellow-800',
    borderColor: 'border-yellow-200',
    bgGradient: 'from-yellow-400 to-lime-500',
  },
  {
    id: 's37',
    text: 'Leci buah merah',
    words: ['Leci', 'buah', 'merah'],
    emoji: '🍒🔴',
    color: 'bg-red-50 hover:bg-red-100',
    textColor: 'text-red-700',
    borderColor: 'border-red-200',
    bgGradient: 'from-red-400 to-rose-500',
  },
  {
    id: 's38',
    text: 'Labu kuning besar',
    words: ['Labu', 'kuning', 'besar'],
    emoji: '🎃🟨',
    color: 'bg-orange-50 hover:bg-orange-100',
    textColor: 'text-orange-700',
    borderColor: 'border-orange-200',
    bgGradient: 'from-orange-400 to-amber-500',
  },
  {
    id: 's39',
    text: 'Cabe merah pedas',
    words: ['Cabe', 'merah', 'pedas'],
    emoji: '🌶️🔥',
    color: 'bg-red-50 hover:bg-red-100',
    textColor: 'text-red-800',
    borderColor: 'border-red-200',
    bgGradient: 'from-red-500 to-rose-600',
  },
  {
    id: 's40',
    text: 'Pipi adik merah',
    words: ['Pipi', 'adik', 'merah'],
    emoji: '😊👶',
    color: 'bg-pink-50 hover:bg-pink-100',
    textColor: 'text-pink-700',
    borderColor: 'border-pink-200',
    bgGradient: 'from-pink-300 to-rose-400',
  },
  {
    id: 's41',
    text: 'Kaki kakak kuat',
    words: ['Kaki', 'kakak', 'kuat'],
    emoji: '👣💪',
    color: 'bg-blue-50 hover:bg-blue-100',
    textColor: 'text-blue-700',
    borderColor: 'border-blue-200',
    bgGradient: 'from-teal-400 to-blue-500',
  },
  {
    id: 's42',
    text: 'Peta dunia indah',
    words: ['Peta', 'dunia', 'indah'],
    emoji: '🗺️🌸',
    color: 'bg-cyan-50 hover:bg-cyan-100',
    textColor: 'text-cyan-705',
    borderColor: 'border-cyan-200',
    bgGradient: 'from-cyan-400 to-blue-500',
  },
  {
    id: 's43',
    text: 'Tisu putih bersih',
    words: ['Tisu', 'putih', 'bersih'],
    emoji: '🧻✨',
    color: 'bg-slate-50 hover:bg-slate-100',
    textColor: 'text-slate-600',
    borderColor: 'border-slate-200',
    bgGradient: 'from-slate-200 to-zinc-400',
  },
  {
    id: 's44',
    text: 'Pita merah muda',
    words: ['Pita', 'merah', 'muda'],
    emoji: '🎀💗',
    color: 'bg-rose-50 hover:bg-rose-100',
    textColor: 'text-rose-600',
    borderColor: 'border-rose-200',
    bgGradient: 'from-rose-400 to-pink-500',
  },
  {
    id: 's45',
    text: 'Bata merah kuat',
    words: ['Bata', 'merah', 'kuat'],
    emoji: '🧱💪',
    color: 'bg-red-50 hover:bg-red-100',
    textColor: 'text-red-700',
    borderColor: 'border-red-200',
    bgGradient: 'from-red-400 to-orange-500',
  },
  {
    id: 's46',
    text: 'Dadu bersisi enam',
    words: ['Dadu', 'bersisi', 'enam'],
    emoji: '🎲🎲',
    color: 'bg-indigo-50 hover:bg-indigo-100',
    textColor: 'text-indigo-700',
    borderColor: 'border-indigo-200',
    bgGradient: 'from-indigo-400 to-violet-500',
  },
  {
    id: 's47',
    text: 'Kopi ayah hitam',
    words: ['Kopi', 'ayah', 'hitam'],
    emoji: '☕◼️',
    color: 'bg-amber-50 hover:bg-amber-100',
    textColor: 'text-amber-900',
    borderColor: 'border-amber-200',
    bgGradient: 'from-amber-600 to-yellow-800',
  },
  {
    id: 's48',
    text: 'Paku besi tajam',
    words: ['Paku', 'besi', 'tajam'],
    emoji: '📍⚔️',
    color: 'bg-slate-50 hover:bg-slate-100',
    textColor: 'text-slate-700',
    borderColor: 'border-slate-200',
    bgGradient: 'from-zinc-400 to-slate-500',
  },
  {
    id: 's49',
    text: 'Saku baju robek',
    words: ['Saku', 'baju', 'robek'],
    emoji: '👛👕',
    color: 'bg-rose-50 hover:bg-rose-100',
    textColor: 'text-rose-700',
    borderColor: 'border-rose-200',
    bgGradient: 'from-pink-300 to-rose-450',
  },
  {
    id: 's50',
    text: 'Tali sepatu merah',
    words: ['Tali', 'sepatu', 'merah'],
    emoji: '🪢👟',
    color: 'bg-orange-50 hover:bg-orange-100',
    textColor: 'text-orange-700',
    borderColor: 'border-orange-200',
    bgGradient: 'from-orange-400 to-red-500',
  },
  {
    id: 's51',
    text: 'Raja duduk gagah',
    words: ['Raja', 'duduk', 'gagah'],
    emoji: '👑🤵',
    color: 'bg-yellow-50 hover:bg-yellow-100',
    textColor: 'text-yellow-700',
    borderColor: 'border-yellow-200',
    bgGradient: 'from-amber-400 to-yellow-500',
  },
  {
    id: 's52',
    text: 'Ratu pakai mahkota',
    words: ['Ratu', 'pakai', 'mahkota'],
    emoji: '👸👑',
    color: 'bg-pink-50 hover:bg-pink-100',
    textColor: 'text-pink-700',
    borderColor: 'border-pink-200',
    bgGradient: 'from-pink-400 to-purple-500',
  },
  {
    id: 's53',
    text: 'Singa aum keras',
    words: ['Singa', 'aum', 'keras'],
    emoji: '🦁🔊',
    color: 'bg-amber-50 hover:bg-amber-100',
    textColor: 'text-amber-850',
    borderColor: 'border-amber-200',
    bgGradient: 'from-yellow-500 to-amber-600',
  },
  {
    id: 's54',
    text: 'Bakso bulat enak',
    words: ['Bakso', 'bulat', 'enak'],
    emoji: '🍲😋',
    color: 'bg-orange-50 hover:bg-orange-100',
    textColor: 'text-orange-700',
    borderColor: 'border-orange-200',
    bgGradient: 'from-orange-400 to-amber-600',
  },
  {
    id: 's55',
    text: 'Sofa empuk sekali',
    words: ['Sofa', 'empuk', 'sekali'],
    emoji: '🛋️💤',
    color: 'bg-blue-50 hover:bg-blue-100',
    textColor: 'text-blue-700',
    borderColor: 'border-blue-200',
    bgGradient: 'from-blue-400 to-indigo-500',
  },
  {
    id: 's56',
    text: 'Apel segar manis',
    words: ['Apel', 'segar', 'manis'],
    emoji: '🍎🍬',
    color: 'bg-red-50 hover:bg-red-100',
    textColor: 'text-red-700',
    borderColor: 'border-red-200',
    bgGradient: 'from-red-400 to-rose-500',
  },
  {
    id: 's57',
    text: 'Melon hijau manis',
    words: ['Melon', 'hijau', 'manis'],
    emoji: '🍈🟢',
    color: 'bg-green-50 hover:bg-green-100',
    textColor: 'text-green-700',
    borderColor: 'border-green-200',
    bgGradient: 'from-green-400 to-lime-500',
  },
  {
    id: 's58',
    text: 'Sawi hijau segar',
    words: ['Sawi', 'hijau', 'segar'],
    emoji: '🥬🟢',
    color: 'bg-emerald-50 hover:bg-emerald-100',
    textColor: 'text-emerald-700',
    borderColor: 'border-emerald-200',
    bgGradient: 'from-green-450 to-emerald-600',
  },
];
